= A custom walkthrough

A custom walkthrough that shows users how to do something.

This walkthrough is so super awesome, wow! Everyone will learn so much from it.

fdsfds
fdsfdsf


fdsfdsfds

fd
sfdsf
dsf

== First task

This is the first task, super duper

Some stuff will be done in this task

=== This is the first step

This is the first task, super duper

The first step needs you to do 

[type=verification]
. Check this thing.
. Check that thing

=== This is the second step

The second step needs you to do this other thing.

. One
. Two

[type=verification]
Check that thing.

[start=3]
. Three
. Four

[type=verificationFail]
Breathe. Calm down. Try again. Contact your admin.

[type=verificationSuccess]
Well done. You're clearly a good person.

Woop woop doop doop

[type=verification]
Check one more thing

[type=verificationFail]
Heck 'em!

This is a Che route, I hope: {che-url}

[type=taskResource]
=== Some resources

Woop woop doop doop

[type=taskResource]
=== Some other resources

This is super duper

[time=15]
== Second task

This task has no inner steps. Wow, what a cool feature.

It's just loads of text so I can copy/paste all the jazz I want and it'll just
render ok. Super duper!

==== What about adding a strange heading?

Well that should work too!

=== Ok, now I'll add in a step, and it'll work?

Yep, only h3's are treated as steps . . . that's pretty cool if you ask me

