= A custom walkthrough

This is the first sentence of the walkthrough's preamble. It will be used as the
short description for the walkthrough.

These lines will be included in the long description of the walkthrough. Normally
this content will be shown on the overview page for a walkthough. However, it is
excluded from the short description.

To start a task we need to use a h2 heading.

== First task

This is the overview for the first task in the walkthrough.

It can be spread over multiple paragraphs. To start a step we need to use a h3
heading.

=== Custom blocks

This is the content of the first step. Steps can contain any asciidoc. However,
it can also contain a number of walkthrough-specific blocks. For example, below
is a verification block. This is a paragraph that has been annotated with
`[type=verification]`.

[type=verification]
****
This block will render as a verification box with a yes/no checkbox.

. Check this thing.
. Check that thing
****

=== More custom blocks

This is the second step of the first task. It is started with a h3 heading. Below
we'll include some arbitrary asciidoc, a list, with a verification block in the
middle of it. We need to use `[start=3]` annotation to continue the numbering of
the list that the verification block has broken.

Also in this step is the two other types of verification block. These are used to
define content that is shown when a user selects either `yes` or `no` on the
checkbox. These are blocks annotated with `[type=verificationSuccess]` and
`[type=verificationFail]` respectively.

. First item
. Second item

[type=verification]
A second verification block.

[start=3]
. Third item, I should have a 3 beside me
. Fourth item

[type=verificationFail]
A message to show when the user clicks `no`.

[type=verificationSuccess]
A message to show when the user clicks `yes`.

Note that each verification block is a single block. Meaning there cannot be
newlines in the block itself. This can be worked around by surrounding the separate
paragraphs with `\****` or by any other means that maintains a single block of text.

=== Using walkthrough attributes

By default, a number of attributes about the environment will be provided to us.
These attributes will include information such as the URLs of services. One of
these attributes is the URL of Eclipse Che running in the cluster. This attribute
is named `che-url`. We can access it like any other attribute in asciidoc, by
surrounding it with `{}`.

* OpenShift App Host: `{openshift-app-host}`
* Che URL: `{che-url}`.
* Fuse URL: `{fuse-url}`
* Launcher URL: `{launcher-url}`
* API Management URL: `{api-management-url}`
* AMQ URL: `{amq-url}`
* AMQ Broker URL: `{amq-broker-url}`
* AMQ Credential Username: `{amq-credentials-username}`
* AMQ Credential Password: `{amq-credentials-password}`
* EnMasse URL: `{enmasse-url}`
* EnMasse Broker URL: `{enmasse-broker-url}`
* EnMasse Credential Username: `{enmasse-credentials-username}`
* EnMasse Credential Password: `{enmasse-credentials-password}`

[type=taskResource]
=== A task resource

A step-level annotation can be used to add resources to the right-hand side of
the walkthrough in the extra resources section. Any step annotated with
`[type=taskResource]` will be included on the right-hand side instead of being
included in the main content. Note that verification blocks will not work in here,
these steps are treated as raw asciidoc.

[time=15]
== Second task

This is the second task of the walkthrough. On this task we have specified a time
in minutes that the task will take. This can be done using the `[time=15]` annotation,
where `15` is the amount of minutes the task will take. This information will be
used when displaying any overview pages for the walkthrough. If a `time` is not
set on a task, it will be treated as `0` minutes.

Tasks do not need to be split into steps. They can just be raw asciidoc dropped into
the file. So as long as we do not include a h3 section in this task, there will be
no steps in the task.

==== A h4 heading

Only h3 headings are treated as steps, so adding in a h4 heading is treated as
raw asciidoc. This also means that verification blocks cannot be specified in
these blocks.

