// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>


[id='creating-http-connection-in-fuse_{context}']
[.integr8ly-docs-header]
===== 1.3 Creating HTTP connection to CRUD App

ifdef::location[]
// tag::intro[]
To send messages to the Spring Boot app, you create a connection in Red Hat Fuse Online.
// end::intro[]
endif::location[]


. Log in to the link:{fuse-url}[Red Hat Fuse Online, window={target}] console.

. Select *Connections* from the left hand menu.

. Select the *Create Connection* button to start the *Create Connection* wizard.

. When prompted with *Select Connector*, select *Walkthrough {walkthrough-id} CRUD Connector*.

. When prompted with *Walkthrough {walkthrough-id} CRUD Configuration*, click *Next*.

. When prompted with *Add Connection Details*:
.. Enter the following in the *Connection Name* field:
+
[subs="attributes+"]
----  
Walkthrough {walkthrough-id} CRUD App
----
.. Click *Create*.

ifdef::location[]

.To verify this procedure:
// tag::verification[]
Check the *Connections* screen of the link:{fuse-url}[Red Hat Fuse Online, window={target}] console to make sure the new connection exists.
// end::verification[]

.If your verification fails:
// tag::verificationNo[]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.
// end::verificationNo[]
endif::location[]
