
[id='creating-amqp-connection-in-fuse_{context}']

= Creating an AMQ connection

ifdef::location[]
// tag::intro[]
To receive messages from {messaging-service}, you create a connection in Red Hat Fuse Online.
// end::intro[]
endif::location[]


. Log in to the link:{fuse-url}[Red Hat Fuse Online, window="_blank"] console.

. Select *Connections* from the left hand menu.

. Select the *Create Connection* button to start the *Create Connection* wizard.

. When prompted with *Select Connector*, select *AMQ Message Broker*.

. When prompted with *AMQ Message Broker Configuration*:
.. Enter the following into the *Broker URL* field: `tcp://{messaging-broker-url}:61616`.
.. Enter the following into the *User Name* field: `{messaging-username}`.
.. Enter the following into the *Password* field: `{messaging-password}`.
.. Select `Disable` for the *Check Certificates* field.
.. Click *Validate*.
.. Click *Next*.

. When prompted for *Add Connection Details*:
.. Enter the following in the *Connection Name* field, `Walkthrough {walkthrough-id} Messaging App`.
.. Click *Create*.


ifdef::location[]

.To verify this procedure:
// tag::verification[]
Check the *Connections* screen of the link:{fuse-url}[Red Hat Fuse Online, window="_blank"] console to make sure the new connection exists.
// end::verification[]

.If your verification fails:
// tag::verificationNo[]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.
// end::verificationNo[]
endif::location[]
