// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>


[id='creating-fuse-integration_{context}']
[.integr8ly-docs-header]
===== 3.1 Creating an integration

ifdef::location[]
// tag::intro[]
To use the Fuse connections, you create an integration in Red Hat Fuse Online.
// end::intro[]
endif::location[]


. Select *Integrations* from the left hand menu.

. Select the *Create Integration* button to start the *Create Integration* wizard.

. Choose *Walkthrough {walkthrough-id} Messaging App* as the *Start Connection*.

. When prompted to *Choose an Action*, select *Subscribe for messages*.

. When prompted for a *Destination Name*, enter:
+
[subs="attributes+"]
---- 
work-queue-requests
----

. Choose *Queue* as the *Destination Type* and click *Next*.

. When prompted to *Specify Output Data Type*:
.. Select *JSON Schema* as the type.
.. Enter the following in the *Definition* field:
+
[subs="attributes+"]
----
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"type": {
			"type": "string"
		}
	}
}
----
.. Click *Done*.

. Choose *Walkthrough {walkthrough-id} CRUD App* as the *Finish Connection*.

. When prompted to *Choose an Action*, select *Create a fruit*.

. When prompted to *Add to Integration*, select *Add a Step*.

. Select *Data Mapper* to map source and target fields in the corresponding JSON schemas:
.. Click and drag *type* from the *Source* column to *body/name* in the *Target* column.
.. Click *Done* to navigate back to the Integration screen.

. Click *Publish*.
. When prompted, enter a name, for example:
+
[subs="attributes+"]
----  
Walkthrough {walkthrough-id}
----

ifdef::location[]

.To verify this procedure:
// tag::verification[]
Check the *Integrations* screen of the link:{fuse-url}[Red Hat Fuse Online, window="_blank"] console to make sure the new connection exists.
// end::verification[]

.If your verification fails:
// tag::verificationNo[]
Verify that you followed each step in the procedure above.  If you are still having issues, contact your administrator.
// end::verificationNo[]
endif::location[]
