// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// Base the file name and the ID on the module title. For example:
// * file name: doing-procedure-a.adoc
// * ID: [id='doing-procedure-a']
// * Title: = Doing procedure A

// The ID is used as an anchor for linking to the module. Avoid changing it after the module has been published to ensure existing links are not broken.
[id='deploying-fuse-aggregation-app_{context}']
// The `context` attribute enables module reuse. Every module's ID includes {context}, which ensures that the module has a unique ID even if it is reused multiple times in a guide.



= Deploying the Fuse Aggregation App

ifdef::location[]
// tag::intro[]
The Fuse Aggregation App can be deployed using Launcher.
// end::intro[]
endif::location[]

// TODO placeholders for product names
// TODO append /launch/wizard/<project-name> to launcher url
// TODO flights endpoint url
. Log in to the link:{launcher-url}[Launcher, window="_blank"] wizard.

. Select the option to *Code Locally, Build and Deploy* in the *Select Target Environment* step

. Select the *Authorize* button to allow Launcher create resources in the OpenShift cluster. This triggers an OAuth flow, and eventually redirects back to the {launcer-service} wizard.

. Select the blue down-arrow icon to continue the wizard

. Select the *Aggregation* mission and *Fuse* runtime in the *Select Mission & Runtime* step

. Select the blue down-arrow icon to continue the wizard

. Select the *Authorize* button in the *Authorize Git Provider* step. This opens a Github OAuth page, and eventually redirect back to the {launcer-service} wizard.

. Select the blue down-arrow icon to continue the wizard, accepting the git repository name.

. Select the *Set Up Application* button to provision the mission resources to OpenShift. A build fo the *Fuse Aggregation App* will be triggered, and a deployment eventually rolled out.


ifdef::location[]

.Verification
// tag::verification[]
The project in OpenShift has the following running pods:

. Fuse Aggregation App

. Arrivals Server

. Departures Server

The *Fuse Aggregation App* flights endpoint can be reached at link:{fuse-aggregation-app-flights-url}[Flights API], and responds with 8 flights.

// end::verification[]
endif::location[]

