apiVersion: v1
kind: Template
metadata:
  name: tutorial-web-app-source-building-supplement
parameters:
  - name: SOURCE_REPOSITORY_URL
    value: https://github.com/integr8ly/tutorial-web-app
    required: true
  - name: SOURCE_REPOSITORY_REF
    value: development
    required: true
  - name: SOURCE_REPOSITORY_DIR
    value: .
    required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: tutorial-web-app
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: tutorial-web-app
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: tutorial-web-app:latest
    resources:
      limits:
        memory: 2Gi
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange