const LIST_WALKTHROUGH = 'LIST_WALKTHROUGH';
const CREATE_WALKTHROUGH = 'CREATE_WALKTHROUGH';
const REMOVE_WALKTHROUGH = 'REMOVE_WALKTHROUGH';
const GET_AMQ_CREDENTIALS = 'GET_AMQ_CREDENTIALS';
const GET_ENMASSE_CREDENTIALS = 'GET_ENMASSE_CREDENTIALS';
const GET_PROVISIONING_USER = 'GET_PROVISIONING_USER';
const GET_CUSTOM_CONFIG = 'GET_CUSTOM_CONFIG';
const PROVISION_SERVICE = 'PROVISION_SERVICE';

const SERVICE_TYPES = {
  PROVISIONED_SERVICE: 'PROVISIONED_SERVICE'
};

const SERVICE_STATUSES = {
  PROVISIONING: 'PROVISIONING',
  PROVISIONED: 'PROVISIONED',
  DELETING: 'DELETING',
  UNAVAILABLE: 'UNAVAILABLE'
};

export {
  CREATE_WALKTHROUGH,
  REMOVE_WALKTHROUGH,
  LIST_WALKTHROUGH,
  GET_AMQ_CREDENTIALS,
  GET_ENMASSE_CREDENTIALS,
  GET_PROVISIONING_USER,
  GET_CUSTOM_CONFIG,
  PROVISION_SERVICE,
  SERVICE_STATUSES,
  SERVICE_TYPES
};
