const LIST_WALKTHROUGH = 'LIST_WALKTHROUGH';
const CREATE_WALKTHROUGH = 'CREATE_WALKTHROUGH';
const REMOVE_WALKTHROUGH = 'REMOVE_WALKTHROUGH';
const GET_AMQ_CREDENTIALS = 'GET_AMQ_CREDENTIALS';
const GET_ENMASSE_CREDENTIALS = 'GET_ENMASSE_CREDENTIALS';
const GET_PROVISIONING_USER = 'GET_PROVISIONING_USER';

export { CREATE_WALKTHROUGH, REMOVE_WALKTHROUGH, LIST_WALKTHROUGH, GET_AMQ_CREDENTIALS, GET_ENMASSE_CREDENTIALS, GET_PROVISIONING_USER };
