const GET_THREAD = 'GET_THREAD';
const INIT_THREAD = 'INIT_THREAD';
const UPDATE_THREAD_PROGRESS = 'UPDATE_THREAD_PROGRESS';
const UPDATE_CURRENT_THREAD = 'UPDATE_CURRENT_THREAD';

export { GET_THREAD, INIT_THREAD, UPDATE_THREAD_PROGRESS, UPDATE_CURRENT_THREAD };
