const USER_CREATE = 'USER_CREATE';
const USER_DELETE = 'USER_DELETE';
const USER_INFO = 'USER_INFO';
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';
const USER_STORED_DATA = 'USER_STORED_DATA';
const USER_STORED_DATA_REMOVE = 'USER_STORED_DATA_REMOVE';

export { USER_CREATE, USER_DELETE, USER_INFO, USER_LOGIN, USER_LOGOUT, USER_STORED_DATA, USER_STORED_DATA_REMOVE };
