const GET_WALKTHROUGH_SERVICE = 'GET_WALKTHROUGH_SERVICE';
const GET_WALKTHROUGH = 'GET_WALKTHROUGH';
const GET_WALKTHROUGHS = 'GET_WALKTHROUGHS';
export { GET_WALKTHROUGH, GET_WALKTHROUGHS, GET_WALKTHROUGH_SERVICE };
