const GET_WALKTHROUGH_SERVICE = 'GET_WALKTHROUGH_SERVICE';
const GET_WALKTHROUGH = 'GET_WALKTHROUGH';
const GET_WALKTHROUGHS = 'GET_WALKTHROUGHS';
const GET_WALKTHROUGH_INFO = 'GET_WALKTHROUGH_INFO';
const GET_USER_WALKTHROUGHS = 'GET_USER_WALKTHROUGHS';
const SET_USER_WALKTHROUGHS = 'SET_USER_WALKTHROUGHS';

export {
  GET_WALKTHROUGH_SERVICE,
  GET_WALKTHROUGH,
  GET_WALKTHROUGHS,
  GET_WALKTHROUGH_INFO,
  GET_USER_WALKTHROUGHS,
  SET_USER_WALKTHROUGHS
};
