const GET_WALKTHROUGH_SERVICE = 'GET_WALKTHROUGH_SERVICE';
const GET_WALKTHROUGH = 'GET_WALKTHROUGH';
const GET_WALKTHROUGHS = 'GET_WALKTHROUGHS';
const GET_WALKTHROUGH_INFO = 'GET_WALKTHROUGH_INFO';

export { GET_WALKTHROUGH, GET_WALKTHROUGHS, GET_WALKTHROUGH_INFO, GET_WALKTHROUGH_SERVICE };
