// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

:launcher-name: Red Hat Developer Launcher

[id='running-node-app_{context}']

= Running a Node.js messaging app


:launcher-url: http://launcher-launcher.apps.city.openshiftworkshop.com/
:openshift-url: https://master.city.openshiftworkshop.com/console/project/eval/overview


. Log in to the link:{launcher-url}[{launcher-name}, window={target}] console.

. Select *LAUNCH YOUR PROJECT*.

. Enter a name for your application, for example `my-node-app` and select *Continue*.

. Select *Code Locally, Build and Deploy* to deploy the application on a hosted OpenShift instance. Click the blue down arrow to continue.

.  From the list of missions, select *Messaging Work Queue*. From the list of runtimes, select *Node.js*.
+
Choose the *Integreatly* version of Node.js. Click the blue down arrow to continue.

. Select the *Log in & Authorize Account* button and give OpenShift permissions to your GitHub account. Click the blue down arrow to continue.

. Review your configuration and select *Set Up Application* to create an OpenShift deployment.
+
NOTE: Creating this application automatically creates an OpenShift project of the same name.



