// This assembly is included in the following assemblies:
//
// <List assemblies here, each on a new line>

// Save the context of the assembly that is including this one.
// This is necessary for including assemblies in assemblies.
// See also the complementary step on the last line of this file.

// Base the file name and the ID on the assembly title. For example:
// * file name: my-assembly-a.adoc
// * ID: [id='my-assembly-a']
// * Title: = My assembly A


[id='managing-fuse-aggregation-app-endpoint']


= Using the managed API service


:context: managing-fuse-aggregation-app-endpoint



Unresolved directive in task-calling-fuse-aggregation-app-endpoint.adoc - include::{partialsdir}/calling-fuse-aggregation-app-endpoint-fail-user-key.adoc[leveloffset=2]

Unresolved directive in task-calling-fuse-aggregation-app-endpoint.adoc - include::{partialsdir}/calling-fuse-aggregation-app-endpoint-success.adoc[leveloffset=2]

Unresolved directive in task-calling-fuse-aggregation-app-endpoint.adoc - include::{partialsdir}/calling-fuse-aggregation-app-endpoint-fail-limits.adoc[leveloffset=2]

Unresolved directive in task-calling-fuse-aggregation-app-endpoint.adoc - include::{partialsdir}/fuse-aggregation-app-endpoint-activity-monitoring.adoc[leveloffset=2]




